In [ ]:
from pynamicalsys import DiscreteDynamicalSystem as dds
from pynamicalsys import PlotStyler
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
ds = dds(model="standard map")
k = 1.5

In [3]:
x_range = (0.1, 0.3)
y_range = (0.3, 0.5)

period = 2
grid_size = 1000
tolerance = 2 / grid_size
x = np.linspace(x_range[0], x_range[1], grid_size)
y = np.linspace(y_range[0], y_range[1], grid_size)
X, Y = np.meshgrid(x, y)
grid_points = np.empty((grid_size, grid_size, 2), dtype=np.float64)
grid_points[:, :, 0] = X
grid_points[:, :, 1] = Y

In [4]:
grid_points.max()

0.5

In [5]:
saddle2 = ds.find_periodic_orbit(grid_points, period, parameters=k, tolerance=tolerance, verbose=True, tolerance_decay_factor=0.5, max_iter=1000)

Iter 0: Δorbit=[0.19397653 0.38795307], Δbounds=[0.00100501 0.00100501], tol=2.00e-03
Iter 1: Δorbit=[1.80487169e-06 1.12791156e-05], Δbounds=[0.00099499 0.00099499], tol=1.00e-03
Iter 2: Δorbit=[8.13236846e-07 1.13021572e-05], Δbounds=[5.005005e-06 5.005005e-06], tol=5.00e-04
Iter 3: Δorbit=[1.48412112e-05 3.49416812e-05], Δbounds=[0.00049499 0.00049499], tol=2.50e-04
Iter 4: Δorbit=[1.74679312e-05 3.50246540e-05], Δbounds=[7.40507775e-05 8.29696062e-05], tol=1.25e-04
Iter 5: Δorbit=[4.01961588e-07 3.21620331e-07], Δbounds=[5.09492225e-05 4.20303938e-05], tol=6.25e-05
Iter 6: Δorbit=[2.57847058e-08 2.12454325e-08], Δbounds=[1.15507775e-05 2.04696062e-05], tol=3.13e-05
Iter 7: Δorbit=[5.24157322e-08 5.76479185e-08], Δbounds=[1.96992225e-05 1.07803938e-05], tol=1.56e-05
Iter 8: Δorbit=[1.16398452e-07 1.78576335e-08], Δbounds=[6.43126686e-07 4.84460624e-06], tol=7.81e-06
Iter 9: Δorbit=[1.22049676e-07 1.56483406e-07], Δbounds=[7.16937331e-06 4.24815006e-06], tol=3.91e-06
Iter 10: Δorbit=

In [6]:
saddle2

array([0.19397649, 0.38795298])

In [7]:
# array([0.19397649, 0.38795298]), 42

In [8]:
import numpy as np

a = np.zeros((10, 2))
a[2] = [1, 1]
a[3] = [2, 2]
a[4] = [3, 3]

# Find nonzero rows
nonzero_rows = np.any(a != 0, axis=1)

# Extract nonzero rows into a new array (shape will be 3x2 here)
nonzero_array = a[nonzero_rows]

print(nonzero_array, nonzero_rows)

[[1. 1.]
 [2. 2.]
 [3. 3.]] [False False  True  True  True False False False False False]


In [9]:
count = np.count_nonzero(nonzero_rows)
print(count) 

3


In [10]:
# Count the number of non-zero rows
non_zero_count = np.count_nonzero(a, axis=0)
print("Number of non-zero rows:", non_zero_count)

Number of non-zero rows: [3 3]
