In [1]:
import numpy as np
import matplotlib.pyplot as plt
from pynamicalsys import DiscreteDynamicalSystem as dds

In [2]:
ds = dds(model="standard map")
u = np.array([0.2, 0.5])
parameters = np.array([1.5])
total_time = int(1e6)

In [3]:
ds.lyapunov(u, total_time, parameters=parameters)

array([ 0.2841174, -0.2841174])

In [4]:
ds.lyapunov(u, total_time, parameters=parameters, num_exponents=1)

np.float64(0.2841173973757471)

In [5]:
ds = dds(model="logistic map")

In [6]:
ds.lyapunov(0.2, 1000, parameters=3.8)

np.float64(0.4144271753640285)

In [7]:
ds.lyapunov(0.2, 1000, parameters=3.8, return_history=True)

array([-0.1974758 ,  0.46423697,  0.40527386,  0.53617869,  0.12173674,
        0.30525475,  0.38366076,  0.28385999,  0.38162368,  0.39687455,
        0.42219592,  0.42022787,  0.45231918,  0.39956249,  0.44916312,
        0.44657298,  0.46904009,  0.43045676,  0.46737372,  0.46045534,
        0.48128762,  0.41862282,  0.45281509,  0.46579346,  0.45148577,
        0.47371239,  0.43035473,  0.45758111,  0.46590399,  0.46151033,
        0.47545845,  0.43435997,  0.45762171,  0.46617452,  0.45773487,
        0.47277876,  0.42456034,  0.4454658 ,  0.45545248,  0.43734308,
        0.45449064,  0.45287772,  0.46208018,  0.44317041,  0.45904056,
        0.45982515,  0.46556276,  0.46082996,  0.47103949,  0.33762188,
        0.35511243,  0.36534387,  0.34428258,  0.36006505,  0.3666014 ,
        0.36489717,  0.37498679,  0.33501397,  0.35012624,  0.35883453,
        0.34333931,  0.35688761,  0.36150172,  0.36314054,  0.36932466,
        0.36531569,  0.37524926,  0.3598224 ,  0.3718671 ,  0.37

In [8]:
ds = dds(model="4d symplectic map")

In [9]:
u = [3.0, 0., 0.5, 0.2]
eps1 = 10.5
eps2 = 10.1
xi = 1.001
parameters = [eps1, eps2, xi]

In [10]:
ds.lyapunov(u, 10000, parameters=parameters)

array([ 1.77166084,  1.51770437, -1.51769724, -1.77166797])

In [11]:
ds.lyapunov(u, 10000, parameters=parameters, return_history=True)

array([[ 2.30712957,  1.26517164, -1.23374705, -2.33855415],
       [ 1.5428798 ,  0.77072309, -0.73625291, -1.57734998],
       [ 1.56380115,  0.73989939, -0.70657972, -1.59712082],
       ...,
       [ 1.77164572,  1.51764468, -1.51763754, -1.77165285],
       [ 1.77168896,  1.51768015, -1.51767301, -1.77169609],
       [ 1.77166084,  1.51770437, -1.51769724, -1.77166797]],
      shape=(10000, 4))

In [ ]:
ds.lyapunov(u, 10000, parameters=parameters, num_exponents=2)

array([1.7716162 , 1.51764846])

In [13]:
ds.lyapunov(u, 10000, parameters=parameters, num_exponents=2, return_history=True)

array([[ 2.03528288, -1.39000734],
       [ 1.34042439,  0.16292794],
       [ 1.39578712,  0.56397821],
       ...,
       [ 1.77160107,  1.51758875],
       [ 1.77164432,  1.51762423],
       [ 1.7716162 ,  1.51764846]], shape=(10000, 2))